version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
    - "./bundles:/files"
    - "./nginx:/etc/nginx/conf.d"
  opa:
    image: openpolicyagent/opa
    ports:
      - 8181:8181
    volumes:
      - ./opa:/etc/opa
    command:
      - run
      - --server
      - --log-level=debug
      - -c
      - /etc/opa/config.yaml
    depends_on:
      - nginx